---

- name: 'make sure postgres dependencies are installed'
  package:
    name: python-psycopg2
    state: present
  retries: 3
  register: result
  until: result is succeeded
  when: ansible_os_family == 'Ubuntu'
  tags:
    - python


- name: 'create artifactory database in postgres'
  when: artifactory_database == 'postgresql'
  become: true
  become_user: postgres
  postgresql_db:
    name: artifactory
    state: present
#    owner: "{{ artifactory_username }}"
#    template: 'template0'
#    encoding: 'UTF-8'


- name: 'create artifactory database user in postgres'
  when: artifactory_database == 'postgresql'
  become: true
  become_user: postgres
  postgresql_user:
    db: artifactory
    name: "{{ artifactory_username }}"
    priv: ALL
    password: "{{ artifactory_password }}"
    expires: infinity
    encrypted: true
  tags:
    - users

- name: 'download jdbc connector for postgres'
  when: artifactory_database == 'postgresql'
  get_url:
    url: "{{ postgres_jdbc_url }}"
    dest: "{{ artifactory_home }}/tomcat/lib"
  retries: 3
  register: jdbc_installed
